- SpeedTest.cpp
The bulk portion of the speed test was producing noticeably inconsistent results across multiple runs of SMhaser, on the order over several hundred MB/s. To fix this, I:
* Reversed the order in which the test-with-given alignment loop runs, descending to 0.
* Introduced a short one run warm-up.
With these changes, the results across runs show much tighter clustering consistent with expectations.
> Improve consistency of bulk speed test

- CMakeLists.txt
This fix uses the CMake package `CMP0003` instead of linking directly with `-lpthread`.
It also avoids a CMake warning about policy `CMP0003`.
> fix linker error on Linux

- CMakeLists.txt
- Hashes.h
- farmhash-c-test.cc
- farmhash-c.c
- farmhash-c.h
- farmhash.cc
- farmhash.h
- main.cpp
This adds a farmhash port (C99) to your smhasher.  I tested the port for quality issues and I thought the tests might be helpful for others.  I noticed the current version of farmhash was out of date, so I also updated the implementation (1.1).
I noticed there was one quality issue with the 32 bit hash (Keyset 'Zeroes' Tests), which I haven't had a chance to look into yet.  I left out the results and table updates though since my hardware differs from the hardware that was noted.
If there are any issues with the pull request or anything I can improve, please let me know.
> farmhash updates

- build.sh
Clang now ships with OpenMP support OOB as of LLVM 3.1, so there
is no need to install a 3rd party compiler any longer.
> Using llvm/clang on OS X instead of non-native gcc/g++

- SpeedTest.cpp
- main.cpp
The results of short inputs benchmark don't make any sense. For example, FNV1a of 16-byte input should take at least 3 (latency of IMUL)*16=48 cycles, but according to results, it takes just 26 cycles, which is impossible. And FNV1a of 19-byte keys are faster than FNV1a of 2-byte keys!
The benchmarking of short inputs is broken in two ways:
1. 20 cycles overhead is way too large. Some hash functions are faster than 
donothing() which is absurd. For very small inputs, benchmark mostly measures 
overhead instead of measuring hash function performance.
2. Unlike RDTSCP, RDTSC can be reordered. To make things worse, there is no 
dependency chain between executions of hash function, so they can be executed 
in parrallel by an out-of-order CPU. So in fact the benchmark executes many 
hash …
> Serialize invocations of hash function during benchmarking

- Hashes.cpp
- Hashes.h
- main.cpp
GoodOAAT passes whole SMHasher and has bulk performance greater
than FNV1a (on modern x86).
It could be shortened if avalanche is not an issue (ie if it is
used for hash-tables with prime numbers) in a maner of MicroOAAT.
MicroOAAT - smallest function that passes all collision checks from
SMHasher. It has simpler loop than GoodOAAT, but unfortunately
Clang doesn't produce rotl instruction when `(x>>n|x<<(32-n))` happens
after multiplication, so it is slower than FNV1a with Clang.
> Small One-At-A-Time functions that passes SMHasher

- PMurHash.c
See:
https://chromium-review.googlesource.com/c/angle/angle/+/1117187
https://bugzilla.mozilla.org/show_bug.cgi?id=1471632
> Fix PMurHash.c mingw clang 64-bit compilation.

- .gitignore
- CityTest.cpp
- FarmTest.cc
- Hashes.h
- KeysetTest.cpp
- KeysetTest.h
- Stats.h
- Types.h
- build.sh
- doc/City64high
- doc/City64low
- doc/City64noSeed
- doc/Farm64noSeed
- doc/FarmHash64noSeed
- doc/crc32
- doc/xxh3
- main.cpp
- mum.h
- xxh3.h
- xxhash.c
- xxhash.h
Most SMHasher tests are designed around "small" input length, in order to scout a tractable search space. Unfortunately, many modern hash algorithms feature different code paths depending on the input size. As a consequence, path for large input lengths are not stressed enough, which makes it possible to "pass" the tests, while they were effectively skipped.
Another factor is that computing capacity has increased a lot since SMHasher initial release, and it's now less problematic to run and analyse many more results per test.
This patch proposes to extend test limits, at the cost of higher computation cost.
The most important modifications are : 
- Sparse tests (up to 1.2 KB input)
- Permutation (up to 3 KB input)
- Avalanche (up to 192 bytes input)
There are other minor extension in …
> Expand test limits

- Hashes.cpp
- Hashes.h
- main.cpp
- mir-hash.h
From author of Mum-hash:
> Simple high-quality multiplicative hash passing demerphq-smhsher, faster than spooky, city, or xxhash for strings less 100 bytes. Hash for the same key can be different on different architectures. To get machine-independent hash, use mir_hash_strict which is about 1.5 times slower than mir_hash.
> Add mirhash

- doc/BEBB4185.txt
Noticed that the BEBB4185 (discohash) Sanity value was
```
Verification value 0x66CAC5F2 ....... PASS
```
Which is incorrect. I cloned the latest master and ran the benchmark and got the correct value which should be `0xBEBB4185`
This change updates `/doc/BEBB4185.txt` to reflect that benchmark and the correct Sanity Verification value.
> Correct bebb4185 version and sanity value

- Hashes.cpp
- Hashes.h
- main.cpp
I have reimplemented multiply shift to be faster and correct according to the paper.
They still don't pass all the tests, but they pass Sanity and Hashmap, which is what they were designed to do.
This is follow up on the discussion at https://github.com/rurban/smhasher/commit/fe87441408c77d9b9493128f0c6d7e454013827b .
> New implementations of multiply shift

- Hashes.cpp
I'm having a bit of trouble making the code as fast for byte numbers not a multiple of 8, which is odd, since e.g. 23 bytes should never be slower than 24. E.g. I currently have
```
Small key speed test -   22-byte keys -    26.00 cycles/hash
Small key speed test -   23-byte keys -    27.75 cycles/hash
Small key speed test -   24-byte keys -    22.00 cycles/hash
Small key speed test -   25-byte keys -    24.00 cycles/hash
Small key speed test -   26-byte keys -    25.00 cycles/hash
```
Anyway, this patch makes it slightly better on my system at least.
> Slightly faster handling of odd byte numbers

- .gitignore
- Hashes.cpp
- Hashes.h
- main.cpp
- tabulation.h
I ended up just calling this tabulation for simplicity.
It is a provably correct hash with a tabulation finalizer, so it should work for many advanced purposes like cuckoo hashing, linear probing, similarity estimation etc.
> Added tabulation and fixed mult + poly

- SpeedTest.cpp
While we want to measure the latency of individual hash function
calls, without overlapped execution, doing so by writing to the hashed
buffer causes unrealistic performance issues:
1. forwarding small stores to larger loads does not always work well
2. only loads that overlap with the first 4 byte are slowed down by
a store to those bytes.
Instead, simply derive the address of the hashed data from the
previous iteration's hash.  This change forces *every load* in the
current hash call to depend on the previous hash, and avoids
introducing store forwarding bubbles: we tend to hash strings or
buffers that were initialised a long time before the hash call.
Note how the forwarding pattern makes the previous speed test show a
difference in hash latency for xxh3 on 9-16 bytes, despite …
> SpeedTest: foil out of order execution without store forwarding bubbles

- CMakeLists.txt
In /proc/cpuinfo, " avx512 " doesn't appear to be listed with a space
before and after, as was scanned in CMakeLists.txt before this
commit. Instead, /proc/cpuinfo will show specific subsets of the full
AVX-512 family, like "avx512bw avx512cd avx512dq avx512f avx512vl".
> AVX-512 comes in pieces; scan for any of them

- .travis.yml
- CMakeLists.txt
- Hashes.cpp
- Hashes.h
- halftime-hash.hpp
- main.cpp
HalftimeHash is a tree-hashing variant in which the input is reduced
in size by a constant amount, repeatedly, until very little
remains. This implementation also finalizes with tabulation hashing,
which is 3-independent and doesn't require multiplying large integers.
> Add HalftimeHash

- metrohash/metrohash128crc.cpp
- metrohash/metrohash64crc.cpp
- metrohash/sse2neon.h
Enable ARM64 for sse4.1 by adding sse2neon.h library for arm64.
Updated sse2neon.h header library to metrohash/metrohash128crc.cpp and metrohash/metrohash64crc.cpp file for arm64 platform.
> Enable ARM64 for sse4.1

- Hashes.h
- main.cpp
- pearson_hash/pearsonb.c
- pearson_hash/pearsonb.h
This pull request adds seeding to Pearson B hashing by using a permutation (the regular round permutation) of a given seed as start value for the hash value(s).
Having added this feature to Pearson B, it seems to pass all quality tests – especially those relying on a seed (Seed, PerlinNoise).
> made Pearson B seedable

- DifferentialTest.h
This patch partially addresses #128. It lifts the seeding in the Diff
test to once per function, which doesn't change the semantics since
the seed is always zero anyway.
> Testing Diff on Hash functions with expensive seeding is slow

- jody_hash32.c
- jody_hash32.h
- jody_hash64.c
- jody_hash64.h
- main.cpp
The v6 algorithm uses a better constant and several performance improvements. It now outperforms xxHash64 by about double and outperforms xxh3 by a tiny bit, or at worst is the same speed. The less favorable properties still remain but the collisions are good enough for use in non-secure ways.
> jodyhash: update to version 6

- CMakeLists.txt
- Hashes.h
- main.cpp
- xmsx.c
- xmsx.h
XMSX (XOR - Multiply - Shift - XOR) Hash
Inspired by MUM and Murmur hashes
Design inputs:
- be faster than SW CRC32 on modern 32-bit CPUs (and microcontrollers) (supporting HW 32bx32b->64b multiplication)
- be as simple as possible (small code size)
- try to reuse the same core round function (xor-mul-shift-xor)
- provide reasonable hashing quality (pass SMHasher tests)
XMSX32 passes all SMHasher tests (2 bad seeds)
XMSX64 currently fails one MomentChi2 test (might be fixed later)
> Add new XMSX Hash

- Hashes.h
- main.cpp
- rapidhash.h
Hello,
I wanted to submit 'rapidhash', an improved version of wyhash, to the list of hashes.
There are two variants:
- rapidhash
- rapidhash_unrolled
They compute the same hash, although the unrolled variant has an optimization which should make it run faster on most modern CPUs.
Both should be passing all tests.
They also pass all tests on SMHasher3 (unlike wyhash) and they have an outstanding collision ration when the default seed is used.
The original source code can be found here: https://github.com/Nicoshev/rapidhash
Thanks,
Nicolas
> Add rapidhash

- City.cpp
- City.h
- CityCrc.h
- CityTest.cpp
- Hashes.h
- main.cpp
This PR updates CityHash to [v1.1 commit](https://github.com/google/cityhash/commit/0469694b4609253742bcd3008c0b3f3ba9fcd9ba#diff-55419e66a3f67b0a2ac2c4257bc983004cb389fc0d4af214a13360856f37c9d9). The results are looking fairly similar to the older version. 
Side notes:
- CityHash32 doesn't support seed value in v1.1 code. As alternatives, there are versions that support seeds, like modified  CityHash v1.1.1 from SMHasher3. However, I stick with Google's original repo and simply removed the bad seed test for CityHash32 (`0x2eb38c9f`).
- Added CityCrc256 test. It also doesn't support seed value.
---------------------------
Test results
[City32.txt](https://github.com/user-attachments/files/15906422/City32.txt)
[City64.txt](https://github.com/user-attachments/files/15906423/City64.txt) …
> CityHash updated to v1.1

- Platform.h
- SpeedTest.cpp
SMhasher is quite handy to benchmark hashes while cross-compiling for other platforms, so I'm adding MIPS cycle counter to have estimates based on number of cycles for my OpenWRT routers.
> Add MIPS CPU cycle counter

- AvalancheTest.h
- HashMapTest.cpp
- Hashes.h
- KeysetTest.cpp
- main.cpp
That's a few small fixes those should be easy to review.
I'm submitting them separately to shorten the next PR that'll focus on better SpeedTest reporting and MIPS32 cycle counter.
> Fix 32-bit and big-endian builds

- Hashes.h
- main.cpp
- pearson_hash/portable_endian.h
- pearsonbhash128 and pearsonbhash256 were broken on Windows due to byteswap result being casted to int: `D:\a\smhasher\smhasher\pearson_hash\pearsonb.c(105,10): warning C4013: '_byteswap_uint64' undefined; assuming extern returning int [D:\a\smhasher\smhasher\SMHasherSupport.vcxproj]`
- pearsonbhash64 was broken on big-endian machine
> Fix pearsonbhash{64,128,256}

- .cirrus.yml
- City.cpp
- Platform.h
- SpeedTest.cpp
- main.cpp
Unfortunately, 32-bit cycle counter overflows ≈ twice a minute, so some code is needed to distinguish between meaningful overflow (just add `1<<32` and get the result) and hardly-meaningful (do some math to get the result).
The code might be extended to get rid of `timer_inf` altogether, but it needs clock counter frequency accounting at a timer level and I'm somewhat reluctant to implementing that as this code seems to be good enough.
>  Handle MIPS32 cycle counter overflow

- umash.c
- umash_long.inc
This gets us improved throughput on aarch64, without miscompilation issues on some versions of gcc.
Still no change to the function, so same verification values and stats.
> umash: update to https://github.com/backtrace-labs/umash/tree/fc4c5b6ca1f06c308e96c43aa080bd766238e092
